### ISSUE TITLE
Error - Cannot send an empty message

### ISSUE THREAD

**Issue by cawarduck** [muricans/discord-embedbuilder#12]
Discord now throws an error - Cannot send an empty message

 using addFields command with an array of fields, but now can't see this command anywhere in description.

**Comment by muricans** [comment]
Hi, unfortunately I was not able to replicate this bug.

If you could add some more information, such as discord.js version, screenshots, etc., that would be appreciated.

**Comment by Felanbird** [comment]
I'm closing this issue for now, if you still have this issue and are able to provide more information, I'll re-open it.
