### ISSUE TITLE
 Add support for .addFields()

### ISSUE THREAD

**Issue by MrZillaGold** [muricans/discord-embedbuilder#3]
**Describe the bug**
When trying to use .addFields() for attaching an Field array we get an error. 
It seems that this feature is not implemented in the library.

**Screenshots**
![image](https://user-images.githubusercontent.com/42776347/82939283-7b611880-9fd6-11ea-8ff2-0c26827f2327.png)

[Documentation .addFields()](https://discord.js.org/#/docs/main/stable/class/MessageEmbed?scrollTo=addFields)

**Comment by muricans** [comment]
Sorry, been inactive, I will take a look later today.
