### ISSUE TITLE
Default Emojis don't trigger events

### ISSUE THREAD

**Issue by MrZillaGold** [muricans/discord-embedbuilder#5]
**Describe the bug**
When using default emoji, they do not trigger events when interacting with them

**Comment by muricans** [comment]
I could not replicate the bug being described, but perhaps I'm looking at the wrong thing.
If you could add more details, that would be appreciated.

**Comment by muricans** [comment]
After re looking at your issue, I believe I misread it the first time.
Take a look at d1ea97a if this addresses your problem.

**Comment by MrZillaGold** [comment]
Thanks, judging by the changes the event will be triggered.  If there are any problems, I will reopen this issue
